export enum Boeing737800_TailTypes {
  // noinspection JSUnusedGlobalSymbols (suppresses endless spam of not used)
  PH_BXA = "PH-BXA",
  PH_BXB = "PH-BXB",
  PH_BXC = "PH-BXC",
  PH_BXD = "PH-BXD",
  PH_BXE = "PH-BXE",
  PH_BXF = "PH-BXF",
  PH_BXG = "PH-BXG",
  PH_BXH = "PH-BXH",
  PH_BXI = "PH-BXI",
  PH_BXK = "PH-BXK",
  PH_BXL = "PH-BXL",
  PH_BXM = "PH-BXM",
  PH_BXN = "PH-BXN",
  PH_BXU = "PH-BXN",
  PH_BXV = "PH-BXV",
  PH_BXW = "PH-BXV",
  PH_BXY = "PH-BXY",
  PH_BXZ = "PH-BXZ",
  PH_BGA = "PH-BGA",
  PH_BGB = "PH-BGB",
  PH_BGC = "PH-BGC",
  PH_BCA = "PH-BCA",
  PH_HSD = "PH-HSD",
  PH_HSE = "PH-HSE",
  PH_BCB = "PH-BCB",
  PH_BCD = "PH-BCD",
  PH_BCE = "PH-BCE"
}
